// pbr.js - WebGL2 길에서 쓰는 셰이더들.
//   TERRAIN2 : 지형·탈것·가구가 모두 쓰는 한 프로그램. 기본 / PBR / 애니 세 갈래.
//   SHADOW   : 해 쪽에서 본 깊이만 찍는다.
//   SSAO     : 깊이와 법선으로 구석 그늘을 셈한다.
// 그림 파일은 여전히 하나도 안 쓴다. 노멀·거칠기는 pbrmat.js 가 아틀라스에서 뽑는다.
'use strict';

const SHADOW_SIZE = 2048;

// ── 지형·엔티티 ───────────────────────────────────────────────────────
const TERRAIN2_VS = [
  'precision highp float;',
  'attribute vec3 aPos;',
  'attribute vec2 aUV;',
  'attribute vec3 aLight;',
  'attribute float aNrm;',        // 옥타헤드럴로 접은 법선 (음수면 법선 없음)
  'uniform mat4 uProj;',
  'uniform mat4 uView;',
  'uniform mat4 uModel;',
  'uniform float uTime;',
  'uniform float uWave;',
  'varying vec2 vUV;',
  'varying vec3 vLight;',
  'varying float vDist;',
  'varying vec3 vNrm;',
  'varying vec3 vWorld;',
  'varying float vFlat;',
  UNPACK_NORMAL_GLSL,
  'void main() {',
  '  vec4 world = uModel * vec4(aPos, 1.0);',
  '  if (uWave > 0.5) {',
  '    world.y += sin(world.x * 0.7 + uTime * 2.0) * 0.045',
  '             + sin(world.z * 0.9 + uTime * 1.7) * 0.045 - 0.09;',
  '  }',
  '  vec4 eye = uView * world;',
  '  vDist = length(eye.xyz);',
  '  vUV = aUV;',
  '  vLight = aLight;',
  '  vWorld = world.xyz;',
  '  vNrm = unpackNrm(aNrm);',
  '  vFlat = aNrm < 0.0 ? 1.0 : 0.0;',
  '  gl_Position = uProj * eye;',
  '}'
].join('\n');

const TERRAIN2_FS = [
  'precision highp float;',
  'uniform sampler2D uTex;',
  'uniform sampler2D uNrmTex;',
  'uniform sampler2D uOrmTex;',
  'uniform sampler2D uAOTex;',
  'uniform highp sampler2DShadow uShadowTex;',
  'uniform float uDaylight;',
  'uniform vec3 uFogColor;',
  'uniform float uFogStart;',
  'uniform float uFogEnd;',
  'uniform float uAlphaCut;',
  'uniform vec4 uTint;',
  'uniform float uToon;',
  'uniform vec3 uToonWarm;',
  'uniform vec3 uToonCool;',
  'uniform float uToonSat;',
  // ── PBR ──
  'uniform float uPbr;',          // 0 예전 방식 · 1 물리 기반
  'uniform float uNormalOn;',
  'uniform float uShadowOn;',
  'uniform float uSsaoOn;',
  'uniform mat4 uLightVP;',
  'uniform vec3 uSunDir;',
  'uniform vec3 uSunCol;',
  'uniform vec3 uAmbUp;',
  'uniform vec3 uAmbDn;',
  'uniform vec3 uSkyUp;',
  'uniform vec3 uSkyDn;',
  'uniform vec3 uCamPos;',
  'uniform vec2 uPix;',
  'varying vec2 vUV;',
  'varying vec3 vLight;',
  'varying float vDist;',
  'varying vec3 vNrm;',
  'varying vec3 vWorld;',
  'varying float vFlat;',
  'const float PI = 3.14159265;',
  'float bandv(float x, float n) {',
  '  float s = x * n;',
  '  float i = floor(s);',
  '  return (i + smoothstep(0.40, 0.60, s - i)) / n;',
  '}',
  // 정점에 실린 밝기는 (모서리 그늘 × 면 밝기) 라서, 면 밝기를 도로 나눠
  // 순수한 모서리 그늘만 뽑아낸다. 축에 붙은 면은 표를 그대로 쓴다.
  'float faceShadeOf(vec3 n) {',
  '  vec3 a = abs(n);',
  '  if (a.y > 0.999) return n.y > 0.0 ? 1.0 : 0.55;',
  '  if (a.x > 0.999) return 0.80;',
  '  if (a.z > 0.999) return 0.68;',
  '  return clamp(0.63 + 0.33 * n.y + 0.07 * n.x + 0.04 * n.z, 0.42, 1.0);',
  '}',
  'float D_GGX(float nh, float a) {',
  '  float a2 = a * a;',
  '  float d = nh * nh * (a2 - 1.0) + 1.0;',
  '  return a2 / (PI * d * d + 1e-7);',
  '}',
  'float V_Smith(float nv, float nl, float a) {',
  '  float k = a * 0.5;',
  '  return 0.25 / max(1e-5, (nv * (1.0 - k) + k) * (nl * (1.0 - k) + k));',
  '}',
  'vec3 F_Schlick(vec3 f0, float vh) { return f0 + (1.0 - f0) * pow(1.0 - vh, 5.0); }',
  // 화면 미분으로 접선틀을 세운다. 축에 붙은 블록 면이든 매끈한 탈것이든 다 통한다.
  'mat3 cotangent(vec3 n, vec3 p, vec2 uv) {',
  '  vec3 dp1 = dFdx(p), dp2 = dFdy(p);',
  '  vec2 du1 = dFdx(uv), du2 = dFdy(uv);',
  '  vec3 dp2p = cross(dp2, n), dp1p = cross(n, dp1);',
  '  vec3 t = dp2p * du1.x + dp1p * du2.x;',
  '  vec3 b = dp2p * du1.y + dp1p * du2.y;',
  '  float inv = inversesqrt(max(dot(t, t), dot(b, b)) + 1e-12);',
  '  return mat3(t * inv, b * inv, n);',
  '}',
  'float shadowAt(vec3 p, float nl) {',
  '  vec4 lp = uLightVP * vec4(p, 1.0);',
  '  vec3 q = lp.xyz / lp.w * 0.5 + 0.5;',
  '  if (q.x < 0.002 || q.x > 0.998 || q.y < 0.002 || q.y > 0.998 || q.z > 1.0) return 1.0;',
  '  float bias = mix(0.0012, 0.00022, nl);',
  '  float texel = 1.0 / ' + SHADOW_SIZE.toFixed(1) + ';',
  '  float s = 0.0;',
  '  for (int y = -1; y <= 1; y++) {',
  '    for (int x = -1; x <= 1; x++) {',
  '      s += texture(uShadowTex, vec3(q.xy + vec2(float(x), float(y)) * texel, q.z - bias));',
  '    }',
  '  }',
  '  s /= 9.0;',
  // 가장자리에서 뚝 끊기지 않게 바깥쪽으로 서서히 풀어 준다
  '  vec2 e = abs(q.xy - 0.5) * 2.0;',
  '  float fade = smoothstep(1.0, 0.86, max(e.x, e.y));',
  '  return mix(1.0, s, fade);',
  '}',
  'void main() {',
  '  vec4 tex = texture2D(uTex, vUV);',
  '  if (tex.a < uAlphaCut) discard;',
  '  float sky = vLight.x * uDaylight;',
  // 하늘이 닿는 정도. 낮밤 세기는 uAmbUp/uAmbDn 이 이미 담고 있으므로
  // 여기에 uDaylight 를 또 곱하면 밤에 두 번 어두워져 온 세상이 새까매진다.
  '  float skyVis = clamp(vLight.x, 0.0, 1.0);',
  '  float blk = vLight.y;',
  '  float fog = clamp((vDist - uFogStart) / max(0.001, uFogEnd - uFogStart), 0.0, 1.0);',
  '  vec3 col;',
  '  vec3 gn = normalize(vNrm);',
  '  if (uPbr > 0.5 && vFlat < 0.5) {',
  // ── 물리 기반 ──
  '    vec3 alb = tex.rgb * uTint.rgb;',
  '    vec3 orm = texture2D(uOrmTex, vUV).rgb;',
  '    float cav = orm.r, rough = clamp(orm.g, 0.045, 1.0), metal = orm.b;',
  '    vec3 n = gn;',
  '    if (uNormalOn > 0.5) {',
  '      vec3 tn = texture2D(uNrmTex, vUV).rgb * 2.0 - 1.0;',
  '      n = normalize(cotangent(gn, vWorld, vUV) * tn);',
  '    }',
  '    vec3 v = normalize(uCamPos - vWorld);',
  '    if (dot(n, v) < 0.0 && dot(gn, v) > 0.0) n = gn;',
  '    float nv = max(dot(n, v), 1e-4);',
  '    float nl = max(dot(n, uSunDir), 0.0);',
  // 꼭짓점 그늘 · 결 그늘 · 화면 그늘을 함께 쓴다
  '    float vao = clamp(vLight.z / faceShadeOf(gn), 0.0, 1.0);',
  '    float ao = mix(0.42, 1.0, vao) * mix(0.80, 1.0, cav);',
  '    if (uSsaoOn > 0.5) ao *= texture2D(uAOTex, gl_FragCoord.xy * uPix).r;',
  // 하늘이 안 닿는 굴 속에는 햇빛도 안 든다 (복셀 빛이 이미 알고 있다)
  '    float open = clamp(vLight.x * 1.35, 0.0, 1.0);',
  '    open *= open;',
  '    float sh = (uShadowOn > 0.5) ? shadowAt(vWorld, nl) : 1.0;',
  // 해가 지평선 아래로 넘어가면 직사광을 끈다.
  // 안 그러면 한밤에 땅 밑에서 해가 벽을 비추는 꼴이 된다.
  '    float sunUp = smoothstep(-0.02, 0.14, uSunDir.y);',
  '    vec3 f0 = mix(vec3(0.04), alb, metal);',
  '    vec3 diffCol = alb * (1.0 - metal);',
  '    vec3 h = normalize(uSunDir + v);',
  '    float a = rough * rough;',
  '    vec3 spec = F_Schlick(f0, max(dot(v, h), 0.0)) * D_GGX(max(dot(n, h), 0.0), a)',
  '              * V_Smith(nv, max(nl, 1e-4), a);',
  '    col = (diffCol / PI + spec) * uSunCol * nl * sh * open * uDaylight * sunUp;',
  // 하늘빛 — 위는 하늘, 아래는 땅에서 튄 빛. 하늘 그림 색을 그대로 쓰면 세상이 새파래진다.
  '    vec3 amb = mix(uAmbDn, uAmbUp, n.y * 0.5 + 0.5);',
  '    col += diffCol * amb * ao * max(skyVis, 0.05);',
  // 하늘이 비치는 정도. 프레넬을 날것으로 쓰면 비스듬한 면마다 흰 막이 씌워져
  // 온 세상이 뿌예진다 — 거칠기 제곱으로 눌러 반들한 것에만 남긴다.
  '    vec3 r = reflect(-v, n);',
  '    vec3 skyR = mix(uSkyDn, uSkyUp, r.y * 0.5 + 0.5);',
  '    float gloss = (1.0 - rough) * (1.0 - rough);',
  '    col += skyR * F_Schlick(f0, nv) * gloss * 0.55 * ao * max(skyVis, 0.05);',
  // 횃불·등불 — 따뜻한 색으로 더한다
  '    col += diffCol * vec3(1.00, 0.68, 0.36) * (blk * blk) * 1.55 * ao;',
  '    col += alb * 0.022;',
  '    if (uToon > 0.5) {',
  // 애니 그림체 — PBR 로 셈한 밝기를 단으로 끊고 볕/그늘 색을 입힌다
  '      float k = clamp(dot(col / max(alb, vec3(0.02)), vec3(0.3333)), 0.0, 1.4);',
  '      k = bandv(clamp(k / 1.4, 0.0, 1.0), 3.0);',
  '      vec3 tint = mix(uToonCool, uToonWarm, smoothstep(0.26, 0.70, k));',
  '      col = alb * (0.40 + 0.85 * k) * tint;',
  '      float l = dot(col, vec3(0.2126, 0.7152, 0.0722));',
  '      col = mix(vec3(l), col, uToonSat);',
  '      fog = bandv(fog, 4.0);',
  '    }',
  '  } else if (uToon > 0.5) {',
  '    float lum = max(max(sky, blk), 0.055);',
  '    float lit = bandv(clamp(lum, 0.0, 1.0), 3.0);',
  '    float face = bandv(clamp(vLight.z, 0.0, 1.0), 3.0);',
  '    float k = clamp(lit * face, 0.0, 1.0);',
  '    vec3 tint = mix(uToonCool, uToonWarm, smoothstep(0.26, 0.70, k));',
  '    col = tex.rgb * uTint.rgb * (0.40 + 0.60 * k) * tint;',
  '    float l = dot(col, vec3(0.2126, 0.7152, 0.0722));',
  '    col = mix(vec3(l), col, uToonSat);',
  '    fog = bandv(fog, 4.0);',
  '  } else {',
  '    float lum = max(max(sky, blk), 0.055) * vLight.z;',
  '    col = tex.rgb * uTint.rgb * lum;',
  '  }',
  '  col = mix(col, uFogColor, fog);',
  '  gl_FragColor = vec4(col, tex.a * uTint.a);',
  // 화면 두 번째 장 — SSAO 와 외곽선이 볼 세계 법선
  '  oNrm = vec4(gn * 0.5 + 0.5, 1.0);',
  '}'
].join('\n');

// ── 그림자 지도 ───────────────────────────────────────────────────────
const SHADOW_VS = [
  'precision highp float;',
  'attribute vec3 aPos;',
  'attribute vec2 aUV;',
  'uniform mat4 uLightVP;',
  'uniform mat4 uModel;',
  'varying vec2 vUV;',
  'void main() { vUV = aUV; gl_Position = uLightVP * uModel * vec4(aPos, 1.0); }'
].join('\n');

const SHADOW_FS = [
  'precision highp float;',
  'uniform sampler2D uTex;',
  'varying vec2 vUV;',
  'void main() {',
  '  if (texture2D(uTex, vUV).a < 0.5) discard;',   // 나뭇잎 사이로 빛이 샌다
  '  gl_FragColor = vec4(1.0);',
  '}'
].join('\n');

// ── SSAO ──────────────────────────────────────────────────────────────
const SSAO_FS = [
  'precision highp float;',
  'uniform sampler2D uDepth;',
  'uniform sampler2D uNormal;',
  'uniform mat4 uInvProj;',
  'uniform mat4 uProj;',
  'uniform mat4 uViewOnly;',
  'uniform vec2 uSize;',
  'uniform float uRadius;',
  'uniform float uStrength;',
  'varying vec2 vUV;',
  'vec3 viewPos(vec2 uv) {',
  '  float z = texture2D(uDepth, uv).r * 2.0 - 1.0;',
  '  vec4 c = uInvProj * vec4(uv * 2.0 - 1.0, z, 1.0);',
  '  return c.xyz / c.w;',
  '}',
  'float hash(vec2 p) { return fract(sin(dot(p, vec2(41.3, 289.1))) * 43758.5453); }',
  'void main() {',
  '  float dz = texture2D(uDepth, vUV).r;',
  '  if (dz >= 0.99999) { gl_FragColor = vec4(1.0); return; }',
  '  vec3 p = viewPos(vUV);',
  '  if (-p.z > 90.0) { gl_FragColor = vec4(1.0); return; }',   // 먼 데는 안 판다
  '  vec3 wn = texture2D(uNormal, vUV).xyz * 2.0 - 1.0;',
  '  vec3 n = normalize((uViewOnly * vec4(wn, 0.0)).xyz);',
  '  float ang = hash(vUV * uSize) * 6.2831853;',
  '  float ca = cos(ang), sa = sin(ang);',
  '  float occ = 0.0;',
  '  const int N = 12;',
  '  for (int i = 0; i < N; i++) {',
  '    float fi = float(i);',
  '    float t = (fi + 0.5) / float(N);',
  '    float r = uRadius * sqrt(t);',
  '    float a2 = fi * 2.399963;',
  '    vec3 dir = vec3(cos(a2), sin(a2), 0.0);',
  '    dir.xy = vec2(dir.x * ca - dir.y * sa, dir.x * sa + dir.y * ca);',
  '    dir.z = 0.35 + 0.65 * t;',
  '    if (dot(dir, n) < 0.0) dir = -dir;',
  '    vec3 sp = p + dir * r;',
  '    vec4 cp = uProj * vec4(sp, 1.0);',
  '    vec2 su = cp.xy / cp.w * 0.5 + 0.5;',
  '    if (su.x < 0.0 || su.x > 1.0 || su.y < 0.0 || su.y > 1.0) continue;',
  '    vec3 q = viewPos(su);',
  '    float diff = q.z - sp.z;',
  '    float range = smoothstep(0.0, 1.0, uRadius / max(0.0001, abs(p.z - q.z)));',
  '    if (diff > 0.02) occ += range;',
  '  }',
  '  float ao = clamp(1.0 - occ / float(N) * uStrength, 0.0, 1.0);',
  // 아주 먼 데서는 슬며시 걷는다
  '  ao = mix(ao, 1.0, smoothstep(55.0, 90.0, -p.z));',
  '  gl_FragColor = vec4(vec3(ao), 1.0);',
  '}'
].join('\n');
